### ISSUE TITLE
rastertools package

### ISSUE THREAD

**Issue by jaimebayes** [mfauvel/SummerSchoolGRSS#1]
Hi, 

I would like to try your scripts but they require the rastertools package, but I could not find it anywhere.
Where can I get it? Can you share it with me?

Thanks in advance, JL

**Comment by mfauvel** [comment]
Hi, 
It's strange the file is in the repo:
https://github.com/mfauvel/SummerSchoolGRSS/blob/master/Codes/rasterTools.py

Could you tell me which script you are running ?

**Comment by jaimebayes** [comment]
Hi, 

You are right, just I did not see it, please accept my apologize.
I just run the first scrip_sample_size and it throws the error "rastertools package does not exist", so I though it was not included within the repo. I suppose it was a path problem, nothing more. 
I would like to run it all the scripts, just for learn how they work.

Thanks for your soon answer, JL
